name: music_podcast
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  flutter_svg: ^1.1.4
  shared_preferences: ^2.0.15
  flutter_screenutil: ^5.5.3+2
  asset_cache: ^2.0.0
  cached_network_image: ^3.2.1
  country_code_picker: ^2.0.2
  pinput: ^2.2.9
  carousel_slider: ^4.1.1
  image_picker: ^0.8.5+3
  syncfusion_flutter_gauges: ^20.2.46
  path_provider: ^2.0.10
  audio_waveforms: ^0.1.4
  flutter_share: ^2.0.0
  fluttertoast: ^8.0.9

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audios/

  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: fonts/PlusJakartaSans-Regular.ttf
          weight: 400
